//admin 后台管理员表


//member 注册会员及登陆表

//customer 客户表
CREATE TABLE `baobei_db`.`customer` (
`cid` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
`username` VARCHAR(45) NOT NULL,
`money` INTEGER UNSIGNED NOT NULL,
`tel` VARCHAR(45) NOT NULL,
`beizhu` LONGTEXT NOT NULL,
`status` INTEGER UNSIGNED NOT NULL DEFAULT 0,
`gaozhi` INTEGER UNSIGNED NOT NULL DEFAULT 0,
`tuijianren` VARCHAR(45) NOT NULL,
PRIMARY KEY (`cid`)
)
ENGINE = InnoDB;

ALTER TABLE `baobei_db`.`customer` ADD COLUMN `date` VARCHAR(45) NOT NULL AFTER `tuijianren`,
ADD COLUMN `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `date`;

//status 状态表
CREATE TABLE `baobei_db`.`status` (
`sid` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
`cid` INTEGER UNSIGNED NOT NULL,
`mid` INTEGER UNSIGNED NOT NULL,
`content` VARCHAR(45) NOT NULL,
`date` VARCHAR(45) NOT NULL,
`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`status` INTEGER UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY (`sid`)
)
ENGINE = InnoDB;

//佣金表
CREATE TABLE `baobei_db`.`money` (
`mid` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
`baobeiren` VARCHAR(45) NOT NULL,
`username` VARCHAR(45) NOT NULL,
`yongjin` INTEGER UNSIGNED NOT NULL,
`date` VARCHAR(45) NOT NULL,
`notes` VARCHAR(45) NOT NULL,
`status` INTEGER UNSIGNED NOT NULL DEFAULT 0,
`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`mid`)
)
ENGINE = InnoDB;